export { Container, Section, Heading, Prose } from './primitives';
export { Button } from './Button';
export { Card, Bento } from './Card';
export { SplitHero, EditorialHero } from './Hero';
export { FAQ, type FaqItem } from './Faq';
export { Breadcrumbs, type Crumb } from './Breadcrumbs';
export { JsonLd } from './JsonLd';
export { Nav } from './Nav';
export { Footer } from './Footer';
export { Fact } from './Fact';
export { StatRow, type Stat } from './StatRow';
export { Disclaimer } from './Disclaimer';
export { LeadForm, type LeadVariant, INVESTMENT_ROUTE_IDS } from './LeadForm';
export { DocumentChecklist, type ChecklistRoute, type ChecklistNationality } from './DocumentChecklist';
export { NewsletterForm } from './NewsletterForm';
export { CheckoutButton } from './CheckoutButton';
export { MagicLinkForm } from './MagicLinkForm';
export { StickyCta } from './StickyCta';
export { PhotoHero, heroTrust, type HeroTrust, type HeroLayout } from './PhotoHero';
export { HeroVideo } from './HeroVideo';
export { IntentTiles } from './IntentTiles';
export { TeamStrip } from './TeamStrip';
export { Disclosure } from './Disclosure';
export { Steps, type Step } from './Steps';
export { Reasons, type Reason } from './Reasons';
export { ArticleCards, type ArticleCard } from './ArticleCards';
export { LeadPanel } from './LeadPanel';
export { HeroContact, WhatsAppButton, WhatsAppFab } from './WhatsApp';
export { WhatsAppIcon } from './WhatsAppIcon';
export { Band, Eyebrow, SectionHeader, type BandTone } from './SectionKit';
// Overhaul 2026-10 (plan §2). Proof components read content/shared/proof.ts
// and render nothing while their data is empty.
export { TrustBar } from './TrustBar';
export { Testimonials, reviewsFor, flagEmoji } from './Testimonials';
export { PriceTable, PRICE_ROUTES, type PriceRoute } from './PriceTable';
export { AfterYouMessage } from './AfterYouMessage';
export { NextSteps } from './NextSteps';
export { Guarantee } from './Guarantee';
export { TeamSection } from './TeamSection';
export { OfficeStrip } from './OfficeStrip';
export { MobileWhatsAppBar } from './MobileWhatsAppBar';
export { BookMockup, TocPreview, SamplePages, ForWhom, ServiceUpsell, GUIDE_COVER } from './GuideSales';
