/**
 * Writes docs/facts-verification.md: every fact in content/shared/facts.ts,
 * what it prints today, its source, and every page that renders it — the list
 * Anton works through to sign facts off (set `verified: true` + verifiedBy /
 * verifiedOn). Run `npm run facts:report` after any content or facts change.
 */
import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join, relative, sep } from 'node:path';
import { facts, localized, type Fact } from '../content/shared/facts';
import { contentHref } from '../src/lib/content-href';
import { SITE_KEYS, siteOrigin, type SiteKey } from '../src/sites/registry';

const ROOT = process.cwd();

function walk(dir: string): string[] {
  return readdirSync(dir, { withFileTypes: true }).flatMap((entry) => {
    const path = join(dir, entry.name);
    if (entry.isDirectory()) return entry.name === 'node_modules' ? [] : walk(path);
    return /\.(tsx?|mdx)$/.test(entry.name) ? [path] : [];
  });
}

/** Best-effort public URL for a source file; null for shared code. */
function whereFor(file: string): string {
  const rel = relative(ROOT, file).split(sep).join('/');
  let m = rel.match(/^content\/([^/]+)\/(.+)\.mdx$/);
  if (m) {
    const [, site, slugPath] = m;
    if (/^(members|updates)\//.test(slugPath)) return `guide member area — ${slugPath} (\`${rel}\`)`;
    if ((SITE_KEYS as readonly string[]).includes(site)) {
      return `${siteOrigin(site as SiteKey)}${contentHref(site as SiteKey, slugPath)} (\`${rel}\`)`;
    }
  }
  m = rel.match(/^src\/app\/\([a-z]+\)\/sites\/([^/]+)\/(.*)page\.tsx$/);
  if (m) {
    const [, site, path] = m;
    const route = '/' + path.replace(/\/$/, '').split('/').filter((s) => s && !s.startsWith('(') && !s.startsWith('_')).join('/');
    return `${siteOrigin(site as SiteKey)}${route === '/' ? '/' : route} (\`${rel}\`)`;
  }
  return `shared code, shown on several pages (\`${rel}\`)`;
}

const files = [...walk(join(ROOT, 'src')), ...walk(join(ROOT, 'content'))].filter(
  (file) => !file.endsWith(join('shared', 'facts.ts')),
);
const uses = new Map<string, Set<string>>();
for (const file of files) {
  const source = readFileSync(file, 'utf8');
  for (const key of Object.keys(facts)) {
    const escaped = key.replace(/\./g, '\\.');
    const re = new RegExp(`(k=\\{?["']${escaped}["']|\\{\\{fact:${escaped}\\}\\}|["']${escaped}["'])`);
    if (re.test(source)) uses.set(key, (uses.get(key) ?? new Set()).add(whereFor(file)));
  }
}

const all = Object.values(facts) as Fact[];
const state = (f: Fact) => (f.verified ? 'Verified' : f.sourced ? 'Published with source — awaiting sign-off' : 'Hedged (not shown as a figure)');
const lines: string[] = [
  '# Facts verification list',
  '',
  'Generated by `npm run facts:report` from `content/shared/facts.ts`. Do not edit by hand.',
  '',
  'How it works: every legal or money figure on the seven sites comes from one register.',
  '**Published with source** facts show the figure today, with the source and date checked (Anton decided',
  'this on 2026-09-26). **Hedged** ones show wording without a figure. To sign one off, check the source,',
  'then set `verified: true`, `verifiedBy` and `verifiedOn` on the entry (or fix `display` and `sourced`).',
  'To pull a figure off every page at once, delete its `sourced` block.',
  '',
  `| Status | Count |`,
  `|---|---|`,
  `| Verified | ${all.filter((f) => f.verified).length} |`,
  `| Published with source, awaiting sign-off | ${all.filter((f) => !f.verified && f.sourced).length} |`,
  `| Hedged | ${all.filter((f) => !f.verified && !f.sourced).length} |`,
  '',
];
for (const group of ['Published with source — awaiting sign-off', 'Hedged (not shown as a figure)', 'Verified']) {
  const inGroup = all.filter((f) => state(f) === group);
  if (!inGroup.length) continue;
  lines.push(`## ${group}`, '');
  for (const fact of inGroup) {
    lines.push(`### ${fact.label}`, '', `- **Key:** \`${fact.key}\``);
    lines.push(`- **Shows (en):** ${localized(fact.sourced || fact.verified ? fact.display : fact.hedged, 'en')}`);
    if (!fact.sourced && !fact.verified) lines.push(`- **Proposed figure (en):** ${localized(fact.display, 'en')}`);
    if (fact.sourced) {
      const label = localized(fact.sourced.label, 'en');
      lines.push(`- **Source:** ${fact.sourced.url ? `[${label}](${fact.sourced.url})` : label} — checked ${fact.sourced.checkedOn}`);
    }
    if (fact.sources.length) lines.push(`- **Other sources:** ${fact.sources.map((u) => `<${u}>`).join(' · ')}`);
    if (fact.note) lines.push(`- **Note:** ${fact.note}`);
    const where = [...(uses.get(fact.key) ?? [])].sort();
    lines.push(`- **Where it appears (${where.length}):**`);
    lines.push(...(where.length ? where.map((w) => `  - ${w}`) : ['  - nowhere yet']));
    lines.push('');
  }
}
writeFileSync(join(ROOT, 'docs', 'facts-verification.md'), lines.join('\n'));
console.log(`docs/facts-verification.md: ${all.length} facts`);
